"""nueva_tabla_usuarios

Revision ID: 16776a7c5c87
Revises: 97ab18f919ce
Create Date: 2026-01-22 20:01:16.185710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16776a7c5c87'
down_revision = '97ab18f919ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
